PROG    =       main
SRCS    = hash_table.c    \
          main.c
OBJS    = $(SRCS:.c=.o)
CC      =       gcc
CFLAGS  =       -g -std=gnu11 -Wall

$(PROG) : $(SRCS)
        $(CC) $(CFLAGS) -o $(PROG) $(SRCS)

$(SRCS): hash_table.h

clean :
        /bin/rm -f $(OBJS) $(PROG)
