CC      = gcc
CFLAGS  = -g -std=gnu11 -Wall
HEADERS = hash_table.h
OBJECTS = main.c hash_table.c

default: program

%.o: %.c $(HEADERS)
    $(CC) $(CFLAGS) -c $< -o $@

program: $(OBJECTS)
    $(CC) $(CFLAGS) $(OBJECTS) -o $@

clean:
    -rm -f $(OBJECTS)
    -rm -f program
