PROG    =       main
MAIN   =       main.o
HASH_TABLE =  hash_table.o
CC      =       gcc
CFLAGS  =       -g -std=gnu11 -Wall

$(PROG) : $(MAIN) $(LIST)
        $(CC) $(CFLAGS) -o $(PROG) $(MAIN) $(HASH_TABLE)

$(MAIN) : main.c

$(HASH_TABLE) : hash_table.h

clean :
        /bin/rm -f $(OBJS) $(PROG)
